global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']
    scheme: http
    timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    scheme: http
    static_configs:
    - targets: ['localhost:9090']

  - job_name: velocity
    scrape_interval: 15s
    scrape_timeout: 5s
    metrics_path: '/velocity/actuator/prometheus'
    scheme: http
    static_configs:
    - targets: ['192.168.1.14:8000']

rule_files:
  - '/etc/prometheus/rules.yml'