version: "3"
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: elasticsearch_velocity
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data/:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    container_name: kibana_velocity
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - elastic

  velocity:
    image: openjdk:8
    volumes:
    - ./velocity/:/usr/src/velocity/
    ports:
    - 8000:8000
    environment:
      LOGS_PATH: "${LOGS_PATH}"
      JCDECAUX_API_KEY: "${JCDECAUX_API_KEY}"
      ELASTIC_HOST: "${ELASTIC_HOST}"
      ELASTIC_PORT: "${ELASTIC_PORT}"
    command: >
      /bin/bash -c "
          sleep 30;
          java -jar /usr/src/velocity/${APP_NAME}-${APP_VERSION}.jar -p ${PID_FILE};
      "
networks:
  elastic: